# -*- coding: utf-8 -*-
"""klasifikace-signalu-mlp.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jAGtAQuhOnTTdNqI05R5Q_CcZS1NEobo
"""

import numpy as np
import matplotlib.pyplot as plt

N = 1000
dim = 100
t=np.linspace(0,10,dim)
X = []
y = []
for i in range(N//2):
  X.append(np.sin(t*np.random.randint(0, 10)+np.random.randint(0, 10))*np.random.rand())
  y.append(1)
  X.append((np.random.rand(dim)-0.5))
  y.append(0)

plt.plot(t,X[0])
plt.plot(t, X[1])
#.plot(t,X[2])
#plt.plot(t, X[3])
plt.show()

# normalizace
X=np.array(X)
y=np.array(y)
print(X.shape)
print(y.shape)
min = np.min(X, axis=1)
max = np.max(X, axis=1)

for i in range(N): # skalovani na 0-1
  X[i] = (X[i]-min[i])/(max[i]-min[i]+1e-3)
plt.plot(t,X[0])
plt.plot(t, X[1])
#.plot(t,X[2])
#plt.plot(t, X[3])
plt.show()
print(np.sum(X))
print(np.sum(y))

from sklearn.model_selection import train_test_split
import tensorflow as tf
from tensorflow.keras import models, layers

def get_model():
  model = models.Sequential()
  model.add(layers.Dense(units = 32, input_shape = (dim,) , activation = 'relu'))
  #model.add(layers.Dropout(0.1))
  model.add(layers.Dense(units = 32, activation='relu'))
  #model.add(layers.Dropout(0.1))
  model.add(layers.Dense(1, activation='sigmoid'))
  model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
  return model

X_tr, X_te, y_tr, y_te = train_test_split(X, y, test_size=0.2)
EPOCHS = 40
model = get_model()
print(model.summary())
history = model.fit(X_tr, y_tr, epochs=EPOCHS, validation_split=0.1)

plt.rcParams["figure.figsize"] = [12,4]
figure, axis = plt.subplots(1, 2)

axis[0].plot(history.history['loss'], label='loss - training data')
axis[0].plot(history.history['val_loss'], label='loss - validating data')
axis[0].grid()
axis[0].set_title('Loss')
axis[0].legend()



axis[1].plot(history.history['accuracy'], label='accuracy - training data')
axis[1].plot(history.history['val_accuracy'], label='accuracy - validating data')
axis[1].grid()
axis[1].set_title('Accuracy')
axis[1].legend()

results = model.evaluate(X_te, y_te)
print("test loss, test acc:", results)